"""empty message

Revision ID: e3f22a8def08
Revises: 
Create Date: 2023-06-09 08:48:58.716815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f22a8def08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('ID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('CPF', sa.VARCHAR(length=11), nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=255), nullable=False),
    sa.Column('CARGO', sa.VARCHAR(length=100), nullable=False),
    sa.Column('SALARIO', sa.DOUBLE(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('CPF')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionario')
    # ### end Alembic commands ###
